//! Sentence boundaries as the JDK's `BreakIterator.getSentenceInstance(Locale.ROOT)` finds them,
//! which is what Lucene's `HMMChineseTokenizer` segments on.
//!
//! The JDK's sentence breaking predates UAX #29 and differs from it in ways that show up on real
//! text (most visibly: a line break is whitespace, not a sentence boundary), so `alyze`'s UAX #29
//! sentence breaker can't be used. What it does, in short: a paragraph separator always ends a
//! sentence; a danda ends one along with the whitespace after it; `!`, `?`, `。` and their
//! fullwidth forms end one along with any closing punctuation, whitespace and one paragraph
//! separator after them; a period ends one only when whitespace and then a non-lowercase letter
//! follow, or when opening punctuation or symbols and then a letter follow, with the boundary
//! placed after the whitespace. Combining marks and format characters are transparent (except
//! for a JDK quirk with isolated ones outside the Basic Multilingual Plane), and a literal U+FFFF
//! ends the text because it is Java's end-of-text sentinel.
//!
//! This module is an original implementation of that behaviour as a small state machine, written
//! to match the JDK boundary for boundary; `testdata/smartcn/golden/*.sentences` (generated by
//! the JDK itself) is the ground truth it is tested against.

use tpuf_icu_properties_211::{CodePointMapData, CodePointMapDataBorrowed, props::GeneralCategory};

/// Invokes `on_boundary` with the byte offset of every sentence boundary in `text`, in order,
/// starting with 0 and ending with `text.len()` (so an empty text yields just 0). Returning `false`
/// stops iteration.
pub(crate) fn for_each_boundary(text: &str, mut on_boundary: impl FnMut(usize) -> bool) {
    if !on_boundary(0) {
        return;
    }
    let mut position = 0;
    while position < text.len() {
        position = next_boundary(text, position);
        if !on_boundary(position) {
            return;
        }
    }
}

/// Java's `CharacterIterator` reports the end of the text as this character, so the JDK treats a
/// literal U+FFFF in the text as the end of it too.
const END_OF_TEXT: char = '\u{FFFF}';

/// Runs the state machine from `start` until it stops or the text ends. The result is the last
/// position at which the machine was in an accepting state, and always at least one character
/// past `start`. Rules whose boundary lies before their last characters (a period followed by
/// whitespace and a capital, say) go through lookahead states: entering one records the position
/// after the current character, and reaching [`State::BreakAtLookahead`] makes that recorded
/// position the result.
fn next_boundary(text: &str, start: usize) -> usize {
    let mut result = after_char(text, start);
    let mut lookahead_result = 0;
    let mut state = State::Scanning;
    let mut position = start;
    let at_end = |position: usize| position >= text.len() || char_at(text, position) == END_OF_TEXT;
    while !at_end(position) && state != State::Stop {
        let category = category_of(char_at(text, position));
        if category != Category::Ignore {
            state = state.next(category);
        }
        match state {
            State::BreakAtLookahead => result = lookahead_result,
            _ if state.is_lookahead() => lookahead_result = after_char(text, position),
            _ if state.is_accepting() => result = after_char(text, position),
            _ => {}
        }
        position = after_char(text, position);
    }
    if at_end(position) && lookahead_result == text.len() {
        result = lookahead_result;
    }
    result
}

fn char_at(text: &str, position: usize) -> char {
    text[position..].chars().next().unwrap()
}

fn after_char(text: &str, position: usize) -> usize {
    position + char_at(text, position).len_utf8()
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Category {
    /// Combining marks and format characters: transparent to the state machine.
    Ignore,
    Comma,
    ParagraphSeparator,
    Period,
    /// `"` and `'`, which can open or close.
    Quote,
    /// `!`, `?` and `。`, with their fullwidth forms.
    Terminator,
    /// Any letter that isn't lowercase.
    OtherLetter,
    LowercaseLetter,
    Danda,
    Digit,
    ClosePunctuation,
    OpenPunctuation,
    Space,
    /// Anything else: symbols, controls, unassigned code points.
    Other,
}

const GENERAL_CATEGORY: CodePointMapDataBorrowed<'static, GeneralCategory> =
    CodePointMapData::<GeneralCategory>::new();

fn is_ignorable(c: char) -> bool {
    matches!(
        GENERAL_CATEGORY.get(c),
        GeneralCategory::NonspacingMark | GeneralCategory::EnclosingMark | GeneralCategory::Format
    )
}

fn category_of(c: char) -> Category {
    match c {
        ',' => Category::Comma,
        '\u{2029}' => Category::ParagraphSeparator,
        '.' | '\u{FF0E}' => Category::Period,
        '"' | '\'' => Category::Quote,
        '!' | '?' | '\u{3002}' | '\u{FF01}' | '\u{FF1F}' => Category::Terminator,
        '\u{0964}' | '\u{0965}' => Category::Danda,
        '\t' | '\n' | '\u{0C}' | '\r' | '\u{2028}' => Category::Space,
        _ if is_ignorable(c) => {
            // The JDK's tables for the supplementary planes lose the "ignore" marking of an
            // ignorable code point whose neighbours aren't ignorable too, giving it the comma's
            // category instead.
            let cp = c as u32;
            let neighbour_ignorable = |n: u32| char::from_u32(n).is_some_and(is_ignorable);
            if cp > 0xFFFF && !neighbour_ignorable(cp - 1) && !neighbour_ignorable(cp + 1) {
                Category::Comma
            } else {
                Category::Ignore
            }
        }
        _ => match GENERAL_CATEGORY.get(c) {
            GeneralCategory::LowercaseLetter => Category::LowercaseLetter,
            GeneralCategory::UppercaseLetter
            | GeneralCategory::TitlecaseLetter
            | GeneralCategory::ModifierLetter
            | GeneralCategory::OtherLetter => Category::OtherLetter,
            GeneralCategory::DecimalNumber
            | GeneralCategory::LetterNumber
            | GeneralCategory::OtherNumber => Category::Digit,
            GeneralCategory::SpaceSeparator => Category::Space,
            GeneralCategory::OpenPunctuation | GeneralCategory::InitialPunctuation => {
                Category::OpenPunctuation
            }
            GeneralCategory::ClosePunctuation | GeneralCategory::FinalPunctuation => {
                Category::ClosePunctuation
            }
            _ => Category::Other,
        },
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum State {
    /// No rule can continue; the boundary is wherever the result was left.
    Stop,
    /// Between sentences' ends: nothing seen that could end one.
    Scanning,
    AfterParagraphSeparator,
    AfterDanda,
    /// A lookahead rule just completed: the boundary is the recorded lookahead position.
    BreakAtLookahead,
    /// A period, possibly followed by more periods and closing punctuation.
    AfterPeriod,
    /// A period and one space.
    AfterPeriodSpace,
    /// A period and two or more spaces.
    AfterPeriodSpaces,
    /// A period and a quote, no space between.
    AfterPeriodQuote,
    /// A period, optional spaces, then opening punctuation or symbols; a letter now breaks.
    AfterPeriodOpener,
    /// Like `AfterPeriodOpener`, but reached after two or more spaces (or a quote without
    /// spaces): anything but a letter or more openers stops the machine.
    AfterPeriodSpacesOpener,
    /// A terminator, possibly followed by more terminators, periods and closing punctuation.
    AfterTerminator,
    AfterTerminatorSpace,
}

impl State {
    /// Whether a boundary may be placed after the character that led here.
    fn is_accepting(self) -> bool {
        matches!(
            self,
            State::Scanning
                | State::AfterParagraphSeparator
                | State::AfterDanda
                | State::BreakAtLookahead
                | State::AfterTerminator
                | State::AfterTerminatorSpace
        )
    }

    /// Whether entering this state records the position after the current character as the
    /// boundary a later [`State::BreakAtLookahead`] will use.
    fn is_lookahead(self) -> bool {
        matches!(
            self,
            State::AfterPeriod
                | State::AfterPeriodSpace
                | State::AfterPeriodSpaces
                | State::AfterPeriodQuote
        )
    }

    fn next(self, category: Category) -> State {
        use Category as C;
        use State as S;
        match self {
            S::Stop | S::AfterParagraphSeparator | S::BreakAtLookahead => S::Stop,
            S::Scanning => match category {
                C::ParagraphSeparator => S::AfterParagraphSeparator,
                C::Period => S::AfterPeriod,
                C::Terminator => S::AfterTerminator,
                C::Danda => S::AfterDanda,
                _ => S::Scanning,
            },
            S::AfterDanda => match category {
                C::Space => S::AfterDanda,
                _ => S::Stop,
            },
            S::AfterPeriod => match category {
                C::ParagraphSeparator => S::AfterParagraphSeparator,
                C::Period | C::ClosePunctuation => S::AfterPeriod,
                C::Quote => S::AfterPeriodQuote,
                C::Terminator => S::AfterTerminator,
                C::Danda | C::Other | C::OpenPunctuation => S::AfterPeriodOpener,
                C::Space => S::AfterPeriodSpace,
                C::Comma | C::OtherLetter | C::LowercaseLetter | C::Digit | C::Ignore => {
                    S::Scanning
                }
            },
            S::AfterPeriodSpace => match category {
                C::ParagraphSeparator => S::AfterParagraphSeparator,
                C::Period => S::AfterPeriod,
                C::Terminator => S::AfterTerminator,
                C::OtherLetter => S::BreakAtLookahead,
                C::Quote | C::Danda | C::Other | C::OpenPunctuation => S::AfterPeriodOpener,
                C::Space => S::AfterPeriodSpaces,
                C::Comma | C::LowercaseLetter | C::Digit | C::ClosePunctuation | C::Ignore => {
                    S::Scanning
                }
            },
            S::AfterPeriodSpaces => match category {
                C::ParagraphSeparator => S::AfterParagraphSeparator,
                C::Period => S::AfterPeriod,
                C::Terminator => S::AfterTerminator,
                C::OtherLetter | C::LowercaseLetter => S::BreakAtLookahead,
                C::Quote | C::Danda | C::Other | C::OpenPunctuation => S::AfterPeriodSpacesOpener,
                C::Space => S::AfterPeriodSpaces,
                C::Comma | C::Digit | C::ClosePunctuation | C::Ignore => S::Scanning,
            },
            S::AfterPeriodQuote => match category {
                C::ParagraphSeparator => S::AfterParagraphSeparator,
                C::Period | C::ClosePunctuation => S::AfterPeriod,
                C::Quote => S::AfterPeriodQuote,
                C::Terminator => S::AfterTerminator,
                C::OtherLetter | C::LowercaseLetter => S::BreakAtLookahead,
                C::Danda | C::Other | C::OpenPunctuation => S::AfterPeriodSpacesOpener,
                C::Space => S::AfterPeriodSpace,
                C::Comma | C::Digit | C::Ignore => S::Scanning,
            },
            S::AfterPeriodOpener => match category {
                C::ParagraphSeparator => S::AfterParagraphSeparator,
                C::Period => S::AfterPeriod,
                C::Terminator => S::AfterTerminator,
                C::OtherLetter | C::LowercaseLetter => S::BreakAtLookahead,
                C::Quote | C::Danda | C::Other | C::OpenPunctuation => S::AfterPeriodOpener,
                C::Comma | C::Digit | C::ClosePunctuation | C::Space | C::Ignore => S::Scanning,
            },
            S::AfterPeriodSpacesOpener => match category {
                C::OtherLetter | C::LowercaseLetter => S::BreakAtLookahead,
                C::Quote | C::Danda | C::Other | C::OpenPunctuation => S::AfterPeriodOpener,
                _ => S::Stop,
            },
            S::AfterTerminator => match category {
                C::ParagraphSeparator => S::AfterParagraphSeparator,
                C::Period | C::Quote | C::Terminator | C::ClosePunctuation => S::AfterTerminator,
                C::Space => S::AfterTerminatorSpace,
                _ => S::Stop,
            },
            S::AfterTerminatorSpace => match category {
                C::ParagraphSeparator => S::AfterParagraphSeparator,
                C::Space => S::AfterTerminatorSpace,
                _ => S::Stop,
            },
        }
    }
}
