[package]
name = "alyze"
version = "0.1.5"
edition = "2024"
rust-version = "1.85"
description = "High-performance text analysis for full-text search"
license = "MIT"
repository = "https://github.com/turbopuffer/alyze"
keywords = ["tokenizer", "unicode", "segmentation", "analysis", "nlp"]
categories = ["text-processing", "internationalization"]
exclude = ["testdata/", "benches/"]

[workspace]
members = ["wasm"]

[dependencies]
ahash = "0.8.12"
phf = { version = "0.13.1", features = ["macros"] }
rust-stemmers = "1.2.0"
tpuf_icu_properties_211 = "7"

[dev-dependencies]
criterion = "0.8.2"
itertools = "0.14.0"
parquet = "57.3.0"
tempfile = "3.25.0"
ureq = "3.2.0"

[[bench]]
name = "wikipedia"
harness = false
