// Dumps the compiled tables behind the JDK's BreakIterator.getSentenceInstance(Locale.ROOT) as a
// Rust source file, so alyze::smartcn::sentence can run the same state machine. The tables are
// what sun.text.RuleBasedBreakIteratorBuilder compiles from the sentence rules in
// sun.text.resources.BreakIteratorRules (see ~/Src/smartcn/jdk/BreakIteratorRules.java).
//
//   java --add-opens java.base/sun.text=ALL-UNNAMED DumpJdkSentenceTables OUT.rs

import java.io.PrintWriter;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.BreakIterator;
import java.util.Locale;

public final class DumpJdkSentenceTables {
  public static void main(String[] args) throws Exception {
    BreakIterator iterator = BreakIterator.getSentenceInstance(Locale.ROOT);
    Class<?> cls = iterator.getClass();
    while (!cls.getName().equals("sun.text.RuleBasedBreakIterator")) cls = cls.getSuperclass();

    Field f = cls.getDeclaredField("numCategories");
    f.setAccessible(true);
    int numCategories = f.getInt(iterator);
    f = cls.getDeclaredField("endStates");
    f.setAccessible(true);
    boolean[] endStates = (boolean[]) f.get(iterator);
    f = cls.getDeclaredField("lookaheadStates");
    f.setAccessible(true);
    boolean[] lookaheadStates = (boolean[]) f.get(iterator);
    Method lookupCategory = cls.getDeclaredMethod("lookupCategory", int.class);
    lookupCategory.setAccessible(true);
    Method lookupState = cls.getDeclaredMethod("lookupState", int.class, int.class);
    lookupState.setAccessible(true);
    int numStates = endStates.length;

    try (PrintWriter out =
        new PrintWriter(Files.newBufferedWriter(Paths.get(args[0]), StandardCharsets.UTF_8))) {
      out.println("// Generated by testdata/smartcn/java/DumpJdkSentenceTables.java from");
      out.println("// " + System.getProperty("java.runtime.name") + " " + System.getProperty("java.runtime.version"));
      out.println("// (Unicode data of that JDK). Do not edit.");
      out.println();
      out.println("/// Category of characters the state machine skips over (combining marks, format chars).");
      out.println("pub(super) const IGNORE: i8 = -1;");
      out.println("pub(super) const NUM_CATEGORIES: usize = " + numCategories + ";");
      out.println("pub(super) const NUM_STATES: usize = " + numStates + ";");
      out.println();
      out.println("/// Category of every code point, as `(first, last, category)` ranges covering");
      out.println("/// 0..=0x10FFFF in order; `IGNORE` marks characters the iterator skips.");
      out.println("pub(super) const CATEGORY_RANGES: &[(u32, u32, i8)] = &[");
      int runStart = 0;
      int runCategory = (Integer) lookupCategory.invoke(iterator, 0);
      int ranges = 0;
      for (int cp = 1; cp <= 0x110000; cp++) {
        int category = cp == 0x110000 ? Integer.MIN_VALUE : (Integer) lookupCategory.invoke(iterator, cp);
        if (category != runCategory) {
          out.printf("    (0x%04X, 0x%04X, %s),%n", runStart, cp - 1, runCategory == -1 ? "IGNORE" : Integer.toString(runCategory));
          ranges++;
          runStart = cp;
          runCategory = category;
        }
      }
      out.println("];");
      out.println();
      out.println("/// Transition table: `STATE_TABLE[state][category]` is the next state; 0 stops.");
      out.println("pub(super) const STATE_TABLE: [[u8; NUM_CATEGORIES]; NUM_STATES] = [");
      for (int state = 0; state < numStates; state++) {
        StringBuilder row = new StringBuilder("    [");
        for (int category = 0; category < numCategories; category++) {
          int next = (Integer) lookupState.invoke(iterator, state, category);
          if (next > 255) throw new IllegalStateException("state table needs more than u8");
          row.append(next).append(category + 1 < numCategories ? ", " : "");
        }
        out.println(row + "],");
      }
      out.println("];");
      out.println();
      out.println("pub(super) const END_STATES: [bool; NUM_STATES] = " + bools(endStates) + ";");
      out.println();
      out.println("pub(super) const LOOKAHEAD_STATES: [bool; NUM_STATES] = " + bools(lookaheadStates) + ";");
      System.err.println(numCategories + " categories, " + numStates + " states, " + ranges + " category ranges");
    }
  }

  private static String bools(boolean[] values) {
    StringBuilder sb = new StringBuilder("[");
    for (int i = 0; i < values.length; i++) sb.append(values[i]).append(i + 1 < values.length ? ", " : "");
    return sb.append("]").toString();
  }
}
